### PR TITLE
Add Checkbox lists tests

### PR DESCRIPTION
**Pull request by summercms**
Screenshot:

image

### CODE REVIEW

**Comment by LukeTowers** [comment]
@ayumi-cloud could you do up the testing page that you had before? I like the idea of having a submenu item that is purely for UI demo pages.

**Comment by summercms** [comment]
@LukeTowers Sure, no problem. Will get on and do that in the next few hours.

**Comment by daftspunk** [comment]
Sorry, @ayumi-cloud @LukeTowers, I disagree with this, save your time

The test plugin is supposed to demonstrate meaningful use cases, not be a dumping ground for disparate UI demonstrations. Find a way to make it meaningful, that is the challenge, that's what creates value and inspires people when they look at this plugin 

That being said, this PR appears ok. Will take a look soon

And perhaps there is room for another plugin that does just demonstrate / test UI -- kitchensink plugin

**Comment by daftspunk** [comment]
I added some meaningful tests in 67f53728736c165fe2b8d0141c7f6ab8bde58bf5 

I also replicated the styling issue and will take a look

Related https://github.com/octobercms/october/issues/4823

**Pull request closed without merging**
