### PR TITLE
Extend Cms\Models\ThemeData

### PR DESCRIPTION
**Pull request by seanthepottingshed**
Demonstration of extending `Cms\Models\ThemeData` in boot method.

### CODE REVIEW

**Comment by daftspunk** [comment]
That's great except you mutilated the rest of the file. Did you forget to turn your linter off?

**Comment by LukeTowers** [comment]
@seanthepottingshed please undo the stylistic changes

**Comment by daftspunk** [comment]
That's OK. This is fixed by https://github.com/octobercms/october/issues/3710

**Comment by seanthepottingshed** [comment]
Sorry about the linting, I was chuffed with myself that I figured out how to do the pull request at all!

hes-a-very-naughty-boy

**Pull request closed without merging**
