### PR TITLE
Add Boot Method for Test Case of extending model to add jsonable property

### PR DESCRIPTION
**Pull request by seanthepottingshed**
Extend `RainLab\Blog\Models\Post` to add repeater field for `vimeo_videos`, ensure that we test `$widget->isNested` property to ensure we descend into the void of **500 Server Error**

### CODE REVIEW

**Comment by seanthepottingshed** [comment]
No too sure what I'm doing here, and I've just realised I've done it on the `master` branch - so apologies for that!

##### Expected behavior
I should be able to extend the Post model to add the `$jsonable` property.

##### Actual behavior
Error displayed as there is no `$jsonable` property on the model to extend.

##### Reproduce steps
Run the following migration:

```php
<?php

namespace October\Test\Updates;

use Schema;
use October\Rain\Database\Updates\Migration;

class UpdateRainLabBlogPostsTable extends Migration
{
    public function up()
    {
        Schema::table('rainlab_blog_posts', function ($table) {
            $table->text('vimeo_videos');
        });
    }

    public function down()
    {
        Schema::table('rainlab_blog_posts', function($table) {
           $table->dropColumn('vimeo_videos');
        });
    }
}

```


##### October build
Latest

**Comment by LukeTowers** [comment]
What issue is this in reference to?

**Comment by LukeTowers** [comment]
Why can't you do something like this @seanthepottingshed 

```
Model::extend(function($model) {
    if (App::isRunningInBackend()) {
        $model->jsonable = ['vimeo_videos'];
    }
}
```
Extending the model to add the `jsonable` property through a reference to a specific model instance isn't going to be in the right location to make sure that the property is always available on saving / loading from the database.

**Comment by alxy** [comment]
``$jsonable`` is a ``protected`` model property, thus it cannot be modified from outside of the model: https://github.com/octobercms/library/blob/master/src/Database/Model.php#L53

The fix in this case would be to implement a setter (``addJsonable($columns = [])``), that already exists for other properties like ``$fillable`` or ``$hidden``.

**EDIT**
Actually I just realized there is a setter for this: https://github.com/octobercms/library/blob/master/src/Database/Model.php#L368
It is named simply ``jsonable()`` and has a public API. We could consider renaming this to match the format of the others. This would of course be a breaking change.

**Comment by seanthepottingshed** [comment]
You lovely, lovely people you!

**Comment by daftspunk** [comment]
So nothing else is needed here?

@alxy The naming should probably stay, it follows Laravel's convention, we want to fit in...

    /**
     * Set the fillable attributes for the model.
     *
     * @param  array  $fillable
     * @return $this
     */
    public function fillable(array $fillable)
    {
        $this->fillable = $fillable;

        return $this;
    }

**Comment by alxy** [comment]
@daftspunk I see, but there is also ``addFillable()`` which actually adds to the array rather than replacing it entirely.

**Comment by seanthepottingshed** [comment]
@alxy @daftspunk So in order to explain to the terminally stupid, how do I solve my problem?

**Comment by alxy** [comment]
@seanthepottingshed Try with the following code:

```
$widget->model->jsonable(['vimeo_videos']);
```

Replace that in your boot() method with the current direct access to the $jsonable property.

**Comment by seanthepottingshed** [comment]
@alxy LEGEND!

**Comment by daftspunk** [comment]
Note a method `addJsonable` has been created for this, so the code can become

```
$model->addJsonable('vimeo_videos');
```

Without wiping out other jsonable definitions. Available in Build 397+

**Comment by seanthepottingshed** [comment]
;)

**Pull request closed without merging**
