### PR TITLE
Add array-field test for octobercms/october#1734

### PR DESCRIPTION
**Pull request by dshoreman**

### CODE REVIEW

**Comment by daftspunk** [comment]
I won't merge this because its not obvious enough what we are testing in the UI.

Using this branch locally I was unable to replicate issue #1734

**Comment by dshoreman** [comment]
It's difficult to make something obvious when the thing you're testing isn't a visible element. In this case, it's the field names. I could've set the labels to match the names, but that would've looked even worse without making the test any more useful.

The admin fields are the ones that don't work. The client ones are there as a working reference.

**Comment by daftspunk** [comment]
Were you able to replicate it here? Can you provide new instructions and I'll try again.

**Comment by dshoreman** [comment]
I installed this plugin in a new install with my tests added before submitting the PR and it replicated just fine:
- Flick both switches on
- Fill all fields with text
- Save the form
- Refresh the page

**Comment by daftspunk** [comment]
I did that today, after refreshing everything was fine. Form looked exactly the same. What build are you using?

**Comment by dshoreman** [comment]
No idea - whatever build was latest when I posted the PR. I gave up and 
used the `group[field_1]` array-type notation in the end, but that ended 
up causing issues with something else.

It's been too long to remember what that something else was: might as 
well close this until someone else has the same issue or I try again 
some day.

**Pull request closed without merging**
